name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - run: echo "installing pip deps"
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
         repository: 'mtararujs/python-greetings'
         path: 'api-tests'
      - name: Install dependencies
        run: |
             cd api-tests
             ls -a
             pip install -r requirements.txt
        shell: bash
      
 deploy-to-dev:
    needs: install-pip-deps
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to dev"
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
         repository: 'mtararujs/python-greetings'
         path: 'dev'
         
      - name: install pm2
        run: npm install -g pm2
        shell: bash
        
      - name: pm2
        run: pm2 start app.py--name dev----port 7001
        shell: bash
 tests-on-dev:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing on dev"
 deploy-to-staging:
    needs: tests-on-dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to staging"
 tests-on-staging:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing on staging"
 deploy-to-preprod:
    needs: tests-on-staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to preprod"
 tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing on preprod"
 deploy-to-prod:
    needs: tests-on-preprod
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying on prod"
 tests-on-prod:
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing on prod"
